version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: mdd-postgres
    environment:
      POSTGRES_DB: mdd_system
      POSTGRES_USER: mdd_user
      POSTGRES_PASSWORD: mdd_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/sql:/docker-entrypoint-initdb.d
    networks:
      - mdd-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: mdd-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mdd-network

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: mdd-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password123
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio_data:/data
    networks:
      - mdd-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: mdd-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - mdd-network

  # Kibana (Optional)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: mdd-kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - mdd-network

  # Prometheus (Monitoring)
  prometheus:
    image: prom/prometheus:latest
    container_name: mdd-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - mdd-network

  # Grafana (Dashboards)
  grafana:
    image: grafana/grafana:latest
    container_name: mdd-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infrastructure/monitoring/grafana:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - mdd-network

volumes:
  postgres_data:
  redis_data:
  minio_data:
  elasticsearch_data:
  prometheus_data:
  grafana_data:

networks:
  mdd-network:
    driver: bridge