import { Injectable } from '@nestjs/common';
import { FleetService } from './fleet.service';

@Injectable()
export class FleetSampleService {
  constructor(private readonly fleetService: FleetService) {}

  async createSampleFleet(): Promise<void> {
    console.log('🚢 Creating sample fleet data...');

    // Sample vessels
    const sampleVessels = [
      {
        imoNumber: '9876543',
        vesselName: 'MV DORIKO EXPLORER',
        callSign: 'HLKD1',
        mmsiNumber: '441234567',
        vesselType: 'CONTAINER',
        flagState: 'Korea',
        portOfRegistry: 'Busan',
        officialNumber: 'KR-2023-001',
        grossTonnage: 158000,
        netTonnage: 95000,
        deadweight: 195000,
        lengthOverall: 366.0,
        beam: 59.0,
        draft: 16.5,
        shipyard: 'Hyundai Heavy Industries',
        buildCountry: 'Korea',
        buildDate: new Date('2018-06-15'),
        hullNumber: 'H-2018-001',
        classificationSociety: 'Korean Register',
        classNotation: 'KR A1 Container Ship',
        owner: 'DORIKO Shipping Co. Ltd.',
        operator: 'DORIKO Shipping Co. Ltd.',
        manager: 'DORIKO Ship Management',
        mainEngineType: 'MAN B&W 11G95ME-C10.5',
        mainEnginePower: 72240,
        propulsionType: 'Fixed Pitch Propeller',
        maxSpeed: 23.0,
        serviceSpeed: 20.5,
        piInsurer: 'Korea P&I Club',
        piExpiryDate: new Date('2025-02-20'),
        hullInsurer: 'Samsung Fire & Marine',
        hullInsuranceExpiry: new Date('2025-03-15'),
        ismCode: 'ISM-KR-2024-001',
        ismExpiryDate: new Date('2027-01-15'),
        ispsCode: 'ISPS-KR-2024-001',
        ispsExpiryDate: new Date('2025-01-15'),
        mlcCertificate: 'MLC-KR-2024-001',
        mlcExpiryDate: new Date('2025-02-15'),
        currentPort: 'Busan',
        destination: 'Long Beach',
        estimatedArrival: new Date('2024-09-15'),
        eediCompliant: true,
        seemCompliant: true,
        tier: 'Tier III',
        ballastWaterTreatment: true,
        masterName: 'Captain Kim Jung-ho',
        shipEmail: 'doriko.explorer@dorikoshipping.com',
        satellitePhone: '+82-70-1234-5678',
        inmarsat: '427123456',
        fuelConsumptionRate: 180.5,
        dailyHfoConsumption: 160.0,
        dailyMdoConsumption: 8.5,
        voyageNumber: 'DOE-2024-08-001',
        cargoDescription: 'Containerized General Cargo',
        cargoQuantity: 18500,
      },
      {
        imoNumber: '9876544',
        vesselName: 'MV PACIFIC CARRIER',
        callSign: 'HLKD2',
        mmsiNumber: '441234568',
        vesselType: 'BULK_CARRIER',
        flagState: 'Korea',
        portOfRegistry: 'Incheon',
        officialNumber: 'KR-2021-002',
        grossTonnage: 98000,
        netTonnage: 65000,
        deadweight: 180000,
        lengthOverall: 325.0,
        beam: 60.0,
        draft: 18.0,
        shipyard: 'Samsung Heavy Industries',
        buildCountry: 'Korea',
        buildDate: new Date('2020-03-20'),
        hullNumber: 'H-2020-002',
        classificationSociety: 'Korean Register',
        classNotation: 'KR A1 Bulk Carrier',
        owner: 'Pacific Maritime Ltd.',
        operator: 'Pacific Maritime Ltd.',
        manager: 'DORIKO Ship Management',
        mainEngineType: 'Wärtsilä RT-flex82T',
        mainEnginePower: 27160,
        propulsionType: 'Fixed Pitch Propeller',
        maxSpeed: 15.5,
        serviceSpeed: 14.0,
        piInsurer: 'Korea P&I Club',
        piExpiryDate: new Date('2025-03-20'),
        hullInsurer: 'Samsung Fire & Marine',
        hullInsuranceExpiry: new Date('2025-04-10'),
        ismCode: 'ISM-KR-2024-002',
        ismExpiryDate: new Date('2027-02-20'),
        ispsCode: 'ISPS-KR-2024-002',
        ispsExpiryDate: new Date('2025-02-20'),
        mlcCertificate: 'MLC-KR-2024-002',
        mlcExpiryDate: new Date('2025-03-20'),
        currentPort: 'Incheon',
        destination: 'Newcastle',
        estimatedArrival: new Date('2024-09-25'),
        eediCompliant: true,
        seemCompliant: true,
        tier: 'Tier II',
        ballastWaterTreatment: true,
        masterName: 'Captain Lee Sang-min',
        shipEmail: 'pacific.carrier@pacificmaritime.com',
        satellitePhone: '+82-70-2345-6789',
        inmarsat: '427234567',
        fuelConsumptionRate: 45.0,
        dailyHfoConsumption: 40.0,
        dailyMdoConsumption: 3.5,
        voyageNumber: 'PC-2024-08-001',
        cargoDescription: 'Iron Ore',
        cargoQuantity: 170000,
      },
      {
        imoNumber: '9876545',
        vesselName: 'MT GOLDEN WAVE',
        callSign: 'HLKD3',
        mmsiNumber: '441234569',
        vesselType: 'TANKER',
        flagState: 'Korea',
        portOfRegistry: 'Ulsan',
        officialNumber: 'KR-2019-003',
        grossTonnage: 150000,
        netTonnage: 95000,
        deadweight: 280000,
        lengthOverall: 330.0,
        beam: 58.0,
        draft: 22.0,
        shipyard: 'Daewoo Shipbuilding',
        buildCountry: 'Korea',
        buildDate: new Date('2019-11-10'),
        hullNumber: 'H-2019-003',
        classificationSociety: 'Korean Register',
        classNotation: 'KR A1 Oil Tanker',
        owner: 'Golden Tanker Holdings',
        operator: 'Golden Maritime Services',
        manager: 'DORIKO Ship Management',
        mainEngineType: 'Hyundai-MAN B&W 7G80ME-C9.5',
        mainEnginePower: 22440,
        propulsionType: 'Fixed Pitch Propeller',
        maxSpeed: 16.5,
        serviceSpeed: 15.0,
        piInsurer: 'Korea P&I Club',
        piExpiryDate: new Date('2025-01-10'),
        hullInsurer: 'Hyundai Marine & Fire',
        hullInsuranceExpiry: new Date('2025-02-05'),
        ismCode: 'ISM-KR-2024-003',
        ismExpiryDate: new Date('2027-03-10'),
        ispsCode: 'ISPS-KR-2024-003',
        ispsExpiryDate: new Date('2025-03-10'),
        mlcCertificate: 'MLC-KR-2024-003',
        mlcExpiryDate: new Date('2025-01-10'),
        currentPort: 'Ulsan',
        destination: 'Singapore',
        estimatedArrival: new Date('2024-09-05'),
        eediCompliant: true,
        seemCompliant: true,
        tier: 'Tier II',
        ballastWaterTreatment: true,
        masterName: 'Captain Park Min-jun',
        shipEmail: 'golden.wave@goldentanker.com',
        satellitePhone: '+82-70-3456-7890',
        inmarsat: '427345678',
        fuelConsumptionRate: 55.0,
        dailyHfoConsumption: 50.0,
        dailyMdoConsumption: 4.0,
        voyageNumber: 'GW-2024-08-001',
        cargoDescription: 'Crude Oil',
        cargoQuantity: 260000,
      },
      {
        imoNumber: '9876546',
        vesselName: 'MV ASIA PIONEER',
        callSign: 'HLKD4',
        mmsiNumber: '441234570',
        vesselType: 'CONTAINER',
        flagState: 'Singapore',
        portOfRegistry: 'Singapore',
        officialNumber: 'SG-2022-001',
        grossTonnage: 220000,
        netTonnage: 140000,
        deadweight: 235000,
        lengthOverall: 400.0,
        beam: 61.0,
        draft: 16.0,
        shipyard: 'Hyundai Heavy Industries',
        buildCountry: 'Korea',
        buildDate: new Date('2022-01-25'),
        hullNumber: 'H-2022-001',
        classificationSociety: 'Lloyd\'s Register',
        classNotation: 'LR A1 Container Ship',
        owner: 'Asia Shipping Ventures',
        operator: 'Asia Shipping Ventures',
        manager: 'DORIKO Ship Management',
        mainEngineType: 'MAN B&W 12G95ME-C10.5',
        mainEnginePower: 78840,
        propulsionType: 'Fixed Pitch Propeller',
        maxSpeed: 24.0,
        serviceSpeed: 22.0,
        piInsurer: 'Singapore Marine P&I',
        piExpiryDate: new Date('2025-01-25'),
        hullInsurer: 'AIG Singapore',
        hullInsuranceExpiry: new Date('2025-02-20'),
        ismCode: 'ISM-SG-2024-001',
        ismExpiryDate: new Date('2027-01-25'),
        ispsCode: 'ISPS-SG-2024-001',
        ispsExpiryDate: new Date('2025-01-25'),
        mlcCertificate: 'MLC-SG-2024-001',
        mlcExpiryDate: new Date('2025-01-25'),
        currentPort: 'Singapore',
        destination: 'Los Angeles',
        estimatedArrival: new Date('2024-09-20'),
        eediCompliant: true,
        seemCompliant: true,
        tier: 'Tier III',
        ballastWaterTreatment: true,
        masterName: 'Captain Tan Wei Ming',
        shipEmail: 'asia.pioneer@asiashipping.com.sg',
        satellitePhone: '+65-6123-4567',
        inmarsat: '563123456',
        fuelConsumptionRate: 220.0,
        dailyHfoConsumption: 200.0,
        dailyMdoConsumption: 12.0,
        voyageNumber: 'AP-2024-08-001',
        cargoDescription: 'Mixed Containerized Cargo',
        cargoQuantity: 22000,
      },
      {
        imoNumber: '9876547',
        vesselName: 'MV NORTHEAST SPIRIT',
        callSign: 'HLKD5',
        mmsiNumber: '441234571',
        vesselType: 'CARGO',
        flagState: 'Japan',
        portOfRegistry: 'Tokyo',
        officialNumber: 'JP-2017-005',
        grossTonnage: 45000,
        netTonnage: 28000,
        deadweight: 65000,
        lengthOverall: 200.0,
        beam: 32.0,
        draft: 12.5,
        shipyard: 'Mitsubishi Heavy Industries',
        buildCountry: 'Japan',
        buildDate: new Date('2017-09-08'),
        hullNumber: 'H-2017-005',
        classificationSociety: 'Nippon Kaiji Kyokai',
        classNotation: 'NK A1 General Cargo',
        owner: 'Northeast Shipping Co.',
        operator: 'Northeast Shipping Co.',
        manager: 'Northeast Marine Services',
        mainEngineType: 'Mitsubishi UEC60LSE',
        mainEnginePower: 11900,
        propulsionType: 'Fixed Pitch Propeller',
        maxSpeed: 18.0,
        serviceSpeed: 16.5,
        piInsurer: 'Japan P&I Club',
        piExpiryDate: new Date('2024-12-08'),
        hullInsurer: 'Tokio Marine',
        hullInsuranceExpiry: new Date('2025-01-15'),
        ismCode: 'ISM-JP-2024-005',
        ismExpiryDate: new Date('2026-09-08'),
        ispsCode: 'ISPS-JP-2024-005',
        ispsExpiryDate: new Date('2024-12-08'),
        mlcCertificate: 'MLC-JP-2024-005',
        mlcExpiryDate: new Date('2024-11-08'),
        currentPort: 'Tokyo',
        destination: 'Manila',
        estimatedArrival: new Date('2024-08-30'),
        eediCompliant: false,
        seemCompliant: true,
        tier: 'Tier I',
        ballastWaterTreatment: false,
        masterName: 'Captain Yamamoto Hiroshi',
        shipEmail: 'northeast.spirit@northeastshipping.jp',
        satellitePhone: '+81-3-1234-5678',
        inmarsat: '431123456',
        fuelConsumptionRate: 28.0,
        dailyHfoConsumption: 25.0,
        dailyMdoConsumption: 2.5,
        voyageNumber: 'NS-2024-08-001',
        cargoDescription: 'Machinery and Steel Products',
        cargoQuantity: 58000,
      },
    ];

    // Create vessels and their certificates
    for (const vesselData of sampleVessels) {
      try {
        const vessel = await this.fleetService.createVessel(vesselData);
        console.log(`✅ Created vessel: ${vessel.vesselName} (IMO: ${vessel.imoNumber})`);

        // Create sample certificates for each vessel
        const sampleCertificates = [
          {
            vesselId: vessel.id,
            certificateType: 'SAFETY_CONSTRUCTION',
            certificateName: 'Safety Construction Certificate',
            certificateNumber: `SSC-${vessel.imoNumber}-2024`,
            issuingAuthorityType: 'FLAG_STATE',
            issuingAuthority: 'Korean Maritime Safety Authority',
            issuingCountry: 'Korea',
            issueDate: new Date('2024-01-15'),
            expiryDate: new Date('2029-01-15'),
            conditions: 'Valid for international voyages',
          },
          {
            vesselId: vessel.id,
            certificateType: 'SAFETY_EQUIPMENT',
            certificateName: 'Safety Equipment Certificate',
            certificateNumber: `SEC-${vessel.imoNumber}-2024`,
            issuingAuthorityType: 'FLAG_STATE',
            issuingAuthority: 'Korean Maritime Safety Authority',
            issuingCountry: 'Korea',
            issueDate: new Date('2024-02-10'),
            expiryDate: new Date('2025-02-10'),
            conditions: 'All safety equipment certified',
          },
          {
            vesselId: vessel.id,
            certificateType: 'IOPP',
            certificateName: 'International Oil Pollution Prevention Certificate',
            certificateNumber: `IOPP-${vessel.imoNumber}-2024`,
            issuingAuthorityType: 'FLAG_STATE',
            issuingAuthority: 'Korean Maritime Safety Authority',
            issuingCountry: 'Korea',
            issueDate: new Date('2024-01-20'),
            expiryDate: new Date('2029-01-20'),
            conditions: 'MARPOL Annex I compliance',
          },
          {
            vesselId: vessel.id,
            certificateType: 'ISM',
            certificateName: 'International Safety Management Certificate',
            certificateNumber: `ISM-${vessel.imoNumber}-2024`,
            issuingAuthorityType: 'CLASSIFICATION_SOCIETY',
            issuingAuthority: 'Korean Register',
            issuingCountry: 'Korea',
            issueDate: new Date('2024-03-05'),
            expiryDate: new Date('2027-03-05'),
            conditions: 'ISM Code compliance verified',
          },
          {
            vesselId: vessel.id,
            certificateType: 'ISPS',
            certificateName: 'International Ship Security Certificate',
            certificateNumber: `ISPS-${vessel.imoNumber}-2024`,
            issuingAuthorityType: 'FLAG_STATE',
            issuingAuthority: 'Korean Coast Guard',
            issuingCountry: 'Korea',
            issueDate: new Date('2024-01-30'),
            expiryDate: new Date('2025-01-30'),
            conditions: 'ISPS Code compliance maintained',
          },
          {
            vesselId: vessel.id,
            certificateType: 'MLC',
            certificateName: 'Maritime Labour Certificate',
            certificateNumber: `MLC-${vessel.imoNumber}-2024`,
            issuingAuthorityType: 'FLAG_STATE',
            issuingAuthority: 'Korean Maritime Labour Authority',
            issuingCountry: 'Korea',
            issueDate: new Date('2024-02-15'),
            expiryDate: new Date('2025-08-15'),
            conditions: 'MLC 2006 compliance verified',
          },
          {
            vesselId: vessel.id,
            certificateType: 'LOAD_LINE',
            certificateName: 'Load Line Certificate',
            certificateNumber: `LL-${vessel.imoNumber}-2024`,
            issuingAuthorityType: 'CLASSIFICATION_SOCIETY',
            issuingAuthority: 'Korean Register',
            issuingCountry: 'Korea',
            issueDate: new Date('2024-01-10'),
            expiryDate: new Date('2029-01-10'),
            conditions: 'Load line marks verified',
          },
        ];

        for (const certData of sampleCertificates) {
          try {
            const certificate = await this.fleetService.createCertificate(certData);
            console.log(`  📜 Created certificate: ${certificate.certificateName}`);
          } catch (error) {
            console.error(`  ❌ Failed to create certificate for ${vessel.vesselName}:`, error.message);
          }
        }

      } catch (error) {
        console.error(`❌ Failed to create vessel ${vesselData.vesselName}:`, error.message);
      }
    }

    console.log('🚢 Sample fleet creation completed!');
  }

  async getFleetSummary(): Promise<any> {
    const statistics = await this.fleetService.getFleetStatistics();
    const alerts = await this.fleetService.getCriticalAlerts();
    
    return {
      totalVessels: statistics.totalVessels,
      totalAlerts: alerts.length,
      vesselsByType: statistics.vesselsByType,
      vesselsByStatus: statistics.vesselsByStatus,
    };
  }
}